// 제네레이터에서 사용하는 상수 정의
export class DATABASE_GENERATOR {
    // Prisma enum 접두사
    static ENUM_PREFIX = '$Enums';
    // Prisma 네임스페이스
    static PRISMA = 'Prisma';
    // class-transformer
    static TRANSFORM = 'Transform';
    // enum 값 제외 함수
    static EXCLUDE_ENUM_VALUE = 'excludeEnumValue';
    // 커스텀 변환 데코레이터
    static readonly CUSTOM_TRANSFORM = {
        PRISMA_DECIMAL: 'PrismaDecimalTransform',
        PRISMA_BIGINT: 'PrismaBigIntTransform',
    };
    // class-validator 데코레이터들
    static readonly VALIDATOR = {
        // 커스텀
        IS_PRISMA_DECIMAL: 'IsPrismaDecimal',
        IS_BIGINT: 'IsBigInt',
        // 기본
        IS_OPTIONAL: 'IsOptional',
        IS_EMPTY: 'IsEmpty',
        IS_NOT_EMPTY: 'IsNotEmpty',
        IS_BOOLEAN: 'IsBoolean',
        IS_DATE: 'IsDate',
        IS_STRING: 'IsString',
        IS_INT: 'IsInt',
        IS_ARRAY: 'IsArray',
        IS_POSITIVE: 'IsPositive',
        IS_NEGATIVE: 'IsNegative',
        MIN_DATE: 'MinDate',
        MAX_DATE: 'MaxDate',
        IS_BOOLEAN_STRING: 'IsBooleanString',
        IS_DATE_STRING: 'IsDateString',
        IS_ALPHA: 'IsAlpha',
        IS_ALPHANUMERIC: 'IsAlphanumeric',
        IS_ASCII: 'IsAscii',
        IS_BASE32: 'IsBase32',
        IS_BASE58: 'IsBase58',
        IS_IBAN: 'IsIBAN',
        IS_BIC: 'IsBIC',
        IS_CREDIT_CARD: 'IsCreditCard',
        IS_ISO4217_CURRENCY_CODE: 'IsISO4217CurrencyCode',
        IS_ETHEREUM_ADDRESS: 'IsEthereumAddress',
        IS_BTC_ADDRESS: 'IsBtcAddress',
        IS_DATA_URI: 'IsDataURI',
        IS_FULL_WIDTH: 'IsFullWidth',
        IS_HALF_WIDTH: 'IsHalfWidth',
        IS_VARIABLE_WIDTH: 'IsVariableWidth',
        IS_HEX_COLOR: 'IsHexColor',
        IS_HSL: 'IsHSL',
        IS_HEXADECIMAL: 'IsHexadecimal',
        IS_OCTAL: 'IsOctal',
        IS_PORT: 'IsPort',
        IS_EAN: 'IsEAN',
        IS_ISIN: 'IsISIN',
        IS_JSON: 'IsJSON',
        IS_JWT: 'IsJWT',
        IS_OBJECT: 'IsObject',
        IS_NOT_EMPTY_OBJECT: 'IsNotEmptyObject',
        IS_LOWERCASE: 'IsLowercase',
        IS_LATLONG: 'IsLatLong',
        IS_LATITUDE: 'IsLatitude',
        IS_LONGITUDE: 'IsLongitude',
        IS_ISO31661_ALPHA_2: 'IsISO31661Alpha2',
        IS_ISO31661_ALPHA_3: 'IsISO31661Alpha3',
        IS_LOCALE: 'IsLocale',
        IS_MONGO_ID: 'IsMongoId',
        IS_MULTIBYTE: 'IsMultibyte',
        IS_SURROGATE_PAIR: 'IsSurrogatePair',
        IS_TAX_ID: 'IsTaxId',
        IS_MAGNET_URI: 'IsMagnetURI',
        IS_FIREBASE_PUSH_ID: 'IsFirebasePushId',
        IS_UPPERCASE: 'IsUppercase',
        IS_MILITARY_TIME: 'IsMilitaryTime',
        IS_TIMEZONE: 'IsTimezone',
        IS_MIME_TYPE: 'IsMimeType',
        IS_SEM_VER: 'IsSemVer',
        IS_ISRC: 'IsISRC',
        IS_RFC_3339: 'IsRFC3339',
        ARRAY_NOT_EMPTY: 'ArrayNotEmpty',
        ALLOW: 'Allow',
        IS_DEFINED: 'IsDefined',
        EQUALS: 'Equals',
        NOT_EQUALS: 'NotEquals',
        IS_IN: 'IsIn',
        IS_NOT_IN: 'IsNotIn',
        IS_NUMBER: 'IsNumber',
        IS_ENUM: 'IsEnum',
        IS_DIVISIBLE_BY: 'IsDivisibleBy',
        MIN: 'Min',
        MAX: 'Max',
        IS_NUMBER_STRING: 'IsNumberString',
        CONTAINS: 'Contains',
        NOT_CONTAINS: 'NotContains',
        IS_DECIMAL: 'IsDecimal',
        IS_BASE64: 'IsBase64',
        IS_BYTE_LENGTH: 'IsByteLength',
        IS_CURRENCY: 'IsCurrency',
        IS_EMAIL: 'IsEmail',
        IS_FQDN: 'IsFQDN',
        IS_RGB_COLOR: 'IsRgbColor',
        IS_IDENTITY_CARD: 'IsIdentityCard',
        IS_PASSPORT_NUMBER: 'IsPassportNumber',
        IS_POSTAL_CODE: 'IsPostalCode',
        IS_MAC_ADDRESS: 'IsMacAddress',
        IS_IP: 'IsIP',
        IS_ISBN: 'IsISBN',
        IS_ISO8601: 'IsISO8601',
        IS_MOBILE_PHONE: 'IsMobilePhone',
        IS_PHONE_NUMBER: 'IsPhoneNumber',
        IS_URL: 'IsURL',
        IS_UUID: 'IsUUID',
        LENGTH: 'Length',
        MIN_LENGTH: 'MinLength',
        MAX_LENGTH: 'MaxLength',
        MATCHES: 'Matches',
        IS_HASH: 'IsHash',
        IS_ISSN: 'IsISSN',
        IS_STRONG_PASSWORD: 'IsStrongPassword',
        ARRAY_CONTAINS: 'ArrayContains',
        ARRAY_NOT_CONTAINS: 'ArrayNotContains',
        ARRAY_MIN_SIZE: 'ArrayMinSize',
        ARRAY_MAX_SIZE: 'ArrayMaxSize',
        ARRAY_UNIQUE: 'ArrayUnique',
        IS_INSTANCE: 'IsInstance',
    };

    // import 맵 키 정의
    static MAP_KEY = {
        PRISMA: 'prisma',
        PRISMA_DECIMAL: 'prisma-decimal',
        PRISMA_BIGINT: 'prisma-bigint',
        CLASS_VALIDATOR: 'class-validator',
        CLASS_TRANSFORM: 'class-transformer',
        IS_BOOLEAN_FN: 'is-boolean-fn',
        EXCLUDE_ENUM_VALUE_FN: 'exclude-enum-value-fn',
    };
}
